version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    environment:
        RABBITMQ_DEFAULT_USER: 'user'
        RABBITMQ_DEFAULT_PASS: 'rahasia'
    volumes:
        - ./.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ./.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  mongo:
    env_file:
      - ./.env
    container_name: 'mongo-sejuta'
    image: mongo:latest
    ports:
      - "${PORT}:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}"
    restart: always
    volumes:
        - ./.docker-conf/mongodb/data/db/:/data/db
